# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtailschemaorg.models
import wagtailschemaorg.registry


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailimages', '0016_deprecate_rendition_filter_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('bio', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtailschemaorg.models.PageLDMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='TestOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('twitter_handle', models.CharField(max_length=15)),
                ('facebook_url', models.URLField()),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtailschemaorg.registry.SiteThingLD, models.Model),
        ),
    ]
